"""Create the production schema baseline.

Revision ID: 0001_production_baseline
Revises:
Create Date: 2026-07-10

This migration contains static PostgreSQL DDL captured from the approved active schema.
It intentionally does not import application models.
"""
from __future__ import annotations

from alembic import op


revision = "0001_production_baseline"
down_revision = None
branch_labels = None
depends_on = None


UPGRADE_STATEMENTS = [
    "CREATE TYPE sourceeventstatus AS ENUM ('NEW', 'CORRELATED', 'CASE_CREATED', 'CLOSED')",
    "CREATE TYPE casestatus AS ENUM ('OPEN', 'TRIAGED', 'INVESTIGATING', 'PLANNED', 'EXECUTING', 'VERIFYING', 'RESOLVED', 'CLOSED', 'ESCALATED')",
    "CREATE TYPE evidencetype AS ENUM ('ALERT', 'LOG', 'METRIC', 'TOPOLOGY', 'COMMAND_OUTPUT', 'CASE_NOTE', 'EXTERNAL_CONTEXT')",
    "CREATE TYPE agenttype AS ENUM ('TRIAGE', 'HISTORICAL', 'INSIGHT', 'REMEDIATION', 'SAFETY_CRITIC')",
    "CREATE TYPE agentrunstatus AS ENUM ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED')",
    "CREATE TYPE claimstatus AS ENUM ('HYPOTHESIS', 'SUPPORTED', 'REJECTED', 'ACTIONABLE')",
    "CREATE TYPE memorytype AS ENUM ('EPISODE', 'PATTERN', 'OUTCOME', 'FEEDBACK')",
    "CREATE TYPE remediationplanstatus AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'EXECUTING', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK', 'CANCELLED')",
    "CREATE TYPE executionrunstatus AS ENUM ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'VERIFYING', 'VERIFIED', 'ROLLED_BACK')",
    'CREATE TABLE site (\n\tid SERIAL NOT NULL, \n\tsite_code VARCHAR(50) NOT NULL, \n\tsite_name VARCHAR(100), \n\tdescription TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tupdated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id)\n)',
    'CREATE INDEX ix_site_id ON site (id)',
    'CREATE UNIQUE INDEX ix_site_site_code ON site (site_code)',
    'CREATE TABLE ssh_credential (\n\tid SERIAL NOT NULL, \n\tname VARCHAR(120) NOT NULL, \n\tusername VARCHAR(120) NOT NULL, \n\tauth_type VARCHAR(20) NOT NULL, \n\tencrypted_password TEXT, \n\tencrypted_private_key TEXT, \n\tencrypted_passphrase TEXT, \n\tport INTEGER NOT NULL, \n\tenabled BOOLEAN, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tupdated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id)\n)',
    'CREATE UNIQUE INDEX ix_ssh_credential_name ON ssh_credential (name)',
    'CREATE INDEX ix_ssh_credential_id ON ssh_credential (id)',
    'CREATE TABLE asset_device (\n\tid SERIAL NOT NULL, \n\tnetbox_device_id INTEGER NOT NULL, \n\tname VARCHAR(120), \n\tdevice_type VARCHAR(120), \n\tsite VARCHAR(120), \n\trole VARCHAR(120), \n\tvendor VARCHAR(120), \n\tstatus VARCHAR(50), \n\tserial VARCHAR(120), \n\tprimary_ip VARCHAR(64), \n\track VARCHAR(120), \n\tposition VARCHAR(32), \n\tface VARCHAR(32), \n\ttags JSON, \n\tlast_synced_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tupdated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id)\n)',
    'CREATE INDEX ix_asset_device_id ON asset_device (id)',
    'CREATE INDEX ix_asset_device_role ON asset_device (role)',
    'CREATE INDEX ix_asset_device_vendor ON asset_device (vendor)',
    'CREATE UNIQUE INDEX ix_asset_device_netbox_device_id ON asset_device (netbox_device_id)',
    'CREATE INDEX idx_asset_device_vendor_site ON asset_device (vendor, site)',
    'CREATE INDEX ix_asset_device_name ON asset_device (name)',
    'CREATE INDEX ix_asset_device_primary_ip ON asset_device (primary_ip)',
    'CREATE INDEX ix_asset_device_status ON asset_device (status)',
    'CREATE INDEX ix_asset_device_site ON asset_device (site)',
    'CREATE TABLE integration_setting (\n\tid SERIAL NOT NULL, \n\tintegration_type VARCHAR(50) NOT NULL, \n\tdisplay_name VARCHAR(120) NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tconfig JSON NOT NULL, \n\tsecrets_encrypted JSON NOT NULL, \n\tnotes TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tPRIMARY KEY (id)\n)',
    'CREATE INDEX ix_integration_setting_id ON integration_setting (id)',
    'CREATE UNIQUE INDEX ix_integration_setting_integration_type ON integration_setting (integration_type)',
    'CREATE INDEX ix_integration_setting_enabled ON integration_setting (enabled)',
    'CREATE TABLE log_scope (\n\tid SERIAL NOT NULL, \n\tscope_key VARCHAR(80) NOT NULL, \n\tdisplay_name VARCHAR(120) NOT NULL, \n\tnetbox_site_id INTEGER, \n\tsite_code_snapshot VARCHAR(80), \n\tsite_name_snapshot VARCHAR(120), \n\taliases JSON NOT NULL, \n\tquery_filter TEXT NOT NULL, \n\tdefault_time_range VARCHAR(64) NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tsort_order INTEGER NOT NULL, \n\tscope_metadata JSON NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tPRIMARY KEY (id)\n)',
    'CREATE INDEX ix_log_scope_site_code_snapshot ON log_scope (site_code_snapshot)',
    'CREATE INDEX ix_log_scope_enabled ON log_scope (enabled)',
    'CREATE INDEX ix_log_scope_id ON log_scope (id)',
    'CREATE INDEX ix_log_scope_display_name ON log_scope (display_name)',
    'CREATE UNIQUE INDEX ix_log_scope_scope_key ON log_scope (scope_key)',
    'CREATE INDEX ix_log_scope_site_name_snapshot ON log_scope (site_name_snapshot)',
    'CREATE INDEX ix_log_scope_netbox_site_id ON log_scope (netbox_site_id)',
    'CREATE TABLE automation_setting (\n\tid SERIAL NOT NULL, \n\tsetting_key VARCHAR(50) NOT NULL, \n\tdisplay_name VARCHAR(120) NOT NULL, \n\tvalue JSON NOT NULL, \n\tnotes TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tPRIMARY KEY (id)\n)',
    'CREATE INDEX ix_automation_setting_id ON automation_setting (id)',
    'CREATE UNIQUE INDEX ix_automation_setting_setting_key ON automation_setting (setting_key)',
    'CREATE TABLE site_automation_switch (\n\tid SERIAL NOT NULL, \n\tsite_id INTEGER NOT NULL, \n\tenabled BOOLEAN NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tupdated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(site_id) REFERENCES site (id)\n)',
    'CREATE INDEX ix_site_automation_switch_enabled ON site_automation_switch (enabled)',
    'CREATE INDEX ix_site_automation_switch_id ON site_automation_switch (id)',
    'CREATE UNIQUE INDEX ix_site_automation_switch_site_id ON site_automation_switch (site_id)',
    'CREATE TABLE device_state (\n\tid SERIAL NOT NULL, \n\tnetbox_device_id INTEGER, \n\tsite_id INTEGER NOT NULL, \n\thealth_score FLOAT, \n\thealth_level VARCHAR(20), \n\tabnormal_flags JSON, \n\tlast_checked_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tupdated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(site_id) REFERENCES site (id)\n)',
    'CREATE INDEX ix_device_state_netbox_device_id ON device_state (netbox_device_id)',
    'CREATE INDEX idx_device_state_site_netbox ON device_state (site_id, netbox_device_id)',
    'CREATE INDEX ix_device_state_id ON device_state (id)',
    'CREATE INDEX ix_device_state_site_id ON device_state (site_id)',
    'CREATE TABLE log_sample (\n\tid SERIAL NOT NULL, \n\tnetbox_device_id INTEGER, \n\tsite_id INTEGER NOT NULL, \n\terror_count INTEGER, \n\tcrc_error_count INTEGER, \n\tflap_count INTEGER, \n\tneighbor_change_count INTEGER, \n\tsampled_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\ttime_window_start TIMESTAMP WITH TIME ZONE, \n\ttime_window_end TIMESTAMP WITH TIME ZONE, \n\tis_abnormal BOOLEAN, \n\traw_data JSON, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(site_id) REFERENCES site (id)\n)',
    'CREATE INDEX ix_log_sample_netbox_device_id ON log_sample (netbox_device_id)',
    'CREATE INDEX ix_log_sample_site_id ON log_sample (site_id)',
    'CREATE INDEX idx_log_sample_site_netbox_time ON log_sample (site_id, netbox_device_id, sampled_at)',
    'CREATE INDEX ix_log_sample_id ON log_sample (id)',
    'CREATE INDEX idx_log_sample_abnormal ON log_sample (site_id, is_abnormal, sampled_at)',
    'CREATE INDEX ix_log_sample_sampled_at ON log_sample (sampled_at)',
    'CREATE TABLE automation_policy (\n\tid SERIAL NOT NULL, \n\tpolicy_code VARCHAR(100) NOT NULL, \n\tpolicy_name VARCHAR(200), \n\tsite_id INTEGER NOT NULL, \n\tpolicy_type VARCHAR(50), \n\ttrigger_type VARCHAR(50), \n\ttrigger_condition JSON, \n\taction JSON, \n\trisk_level VARCHAR(20), \n\trequire_confirm BOOLEAN, \n\tenabled BOOLEAN, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tupdated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(site_id) REFERENCES site (id)\n)',
    'CREATE INDEX ix_automation_policy_site_id ON automation_policy (site_id)',
    'CREATE INDEX ix_automation_policy_id ON automation_policy (id)',
    'CREATE UNIQUE INDEX ix_automation_policy_policy_code ON automation_policy (policy_code)',
    'CREATE TABLE raw_anomaly (\n\tid BIGSERIAL NOT NULL, \n\tsite_id INTEGER NOT NULL, \n\tdevice_id BIGINT, \n\tdevice_ip VARCHAR(45) NOT NULL, \n\ttime_window_start TIMESTAMP WITH TIME ZONE NOT NULL, \n\ttime_window_end TIMESTAMP WITH TIME ZONE NOT NULL, \n\tlog_fingerprint VARCHAR(64) NOT NULL, \n\tlog_samples JSON NOT NULL, \n\tlog_count INTEGER NOT NULL, \n\tbaseline_avg_5m NUMERIC(10, 2), \n\tbaseline_p95_5m NUMERIC(10, 2), \n\tbaseline_count_7d INTEGER, \n\tdeviation_ratio NUMERIC(6, 2), \n\tpre_class VARCHAR(64), \n\tai_class VARCHAR(64), \n\tseverity VARCHAR(16), \n\tconfidence NUMERIC(4, 2), \n\tstatus VARCHAR(32) NOT NULL, \n\tfirst_seen_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tlast_seen_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(site_id) REFERENCES site (id)\n)',
    'CREATE INDEX ix_raw_anomaly_device_ip ON raw_anomaly (device_ip)',
    'CREATE INDEX idx_raw_anomaly_fingerprint ON raw_anomaly (log_fingerprint)',
    'CREATE INDEX ix_raw_anomaly_site_id ON raw_anomaly (site_id)',
    'CREATE INDEX ix_raw_anomaly_device_id ON raw_anomaly (device_id)',
    'CREATE INDEX idx_raw_anomaly_status ON raw_anomaly (site_id, status, first_seen_at)',
    'CREATE UNIQUE INDEX uniq_raw_anomaly_window ON raw_anomaly (site_id, device_id, log_fingerprint, time_window_start)',
    'CREATE INDEX ix_raw_anomaly_log_fingerprint ON raw_anomaly (log_fingerprint)',
    'CREATE INDEX ix_raw_anomaly_time_window_start ON raw_anomaly (time_window_start)',
    'CREATE INDEX idx_raw_anomaly_site_time ON raw_anomaly (site_id, time_window_start)',
    'CREATE INDEX ix_raw_anomaly_id ON raw_anomaly (id)',
    'CREATE INDEX ix_raw_anomaly_status ON raw_anomaly (status)',
    'CREATE TABLE ssh_credential_device_binding (\n\tid SERIAL NOT NULL, \n\tcredential_id INTEGER NOT NULL, \n\tnetbox_device_id INTEGER NOT NULL, \n\tdevice_name VARCHAR(120), \n\tsite_name VARCHAR(120), \n\tplatform VARCHAR(120), \n\trole VARCHAR(120), \n\ttags JSON, \n\tlast_connectivity_status VARCHAR(30), \n\tlast_connectivity_error TEXT, \n\tlast_checked_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tupdated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(credential_id) REFERENCES ssh_credential (id)\n)',
    'CREATE UNIQUE INDEX uniq_credential_device ON ssh_credential_device_binding (credential_id, netbox_device_id)',
    'CREATE INDEX ix_ssh_credential_device_binding_id ON ssh_credential_device_binding (id)',
    'CREATE INDEX idx_binding_site_status ON ssh_credential_device_binding (site_name, last_connectivity_status)',
    'CREATE INDEX ix_ssh_credential_device_binding_credential_id ON ssh_credential_device_binding (credential_id)',
    'CREATE INDEX ix_ssh_credential_device_binding_netbox_device_id ON ssh_credential_device_binding (netbox_device_id)',
    'CREATE TABLE source_event (\n\tid BIGSERIAL NOT NULL, \n\tlegacy_event_id BIGINT, \n\tsource_type VARCHAR(50) NOT NULL, \n\tsource_system VARCHAR(50) NOT NULL, \n\texternal_event_id VARCHAR(128), \n\tdedup_key VARCHAR(128) NOT NULL, \n\tsite_id INTEGER, \n\tnetbox_device_id INTEGER, \n\tdevice_ip VARCHAR(64), \n\thost VARCHAR(255), \n\ttitle VARCHAR(512) NOT NULL, \n\tseverity VARCHAR(30) NOT NULL, \n\tstatus sourceeventstatus NOT NULL, \n\toccurred_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tcollected_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\traw_payload JSON, \n\tnormalized_payload JSON, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tupdated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(site_id) REFERENCES site (id)\n)',
    'CREATE INDEX ix_source_event_site_id ON source_event (site_id)',
    'CREATE INDEX ix_source_event_netbox_device_id ON source_event (netbox_device_id)',
    'CREATE INDEX ix_source_event_device_ip ON source_event (device_ip)',
    'CREATE INDEX ix_source_event_host ON source_event (host)',
    'CREATE INDEX ix_source_event_id ON source_event (id)',
    'CREATE INDEX ix_source_event_external_event_id ON source_event (external_event_id)',
    'CREATE INDEX ix_source_event_collected_at ON source_event (collected_at)',
    'CREATE INDEX idx_source_event_source_status ON source_event (source_system, status, occurred_at)',
    'CREATE INDEX ix_source_event_severity ON source_event (severity)',
    'CREATE INDEX ix_source_event_created_at ON source_event (created_at)',
    'CREATE INDEX idx_source_event_site_device ON source_event (site_id, netbox_device_id, occurred_at)',
    'CREATE UNIQUE INDEX ix_source_event_dedup_key ON source_event (dedup_key)',
    'CREATE INDEX idx_source_event_legacy_event_id ON source_event (legacy_event_id)',
    'CREATE UNIQUE INDEX ix_source_event_legacy_event_id ON source_event (legacy_event_id)',
    'CREATE INDEX ix_source_event_source_system ON source_event (source_system)',
    'CREATE INDEX ix_source_event_occurred_at ON source_event (occurred_at)',
    'CREATE INDEX ix_source_event_source_type ON source_event (source_type)',
    'CREATE INDEX ix_source_event_status ON source_event (status)',
    'CREATE TABLE log_analysis_result (\n\tid SERIAL NOT NULL, \n\tnetbox_device_id INTEGER, \n\tsite_id INTEGER NOT NULL, \n\trelated_sample_id INTEGER, \n\tanalysis_type VARCHAR(50), \n\tconfidence VARCHAR(20), \n\tsummary TEXT, \n\tseverity VARCHAR(20), \n\trecommendation TEXT, \n\tevidence JSON, \n\tstatus VARCHAR(20), \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tupdated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(site_id) REFERENCES site (id), \n\tFOREIGN KEY(related_sample_id) REFERENCES log_sample (id)\n)',
    'CREATE INDEX ix_log_analysis_result_netbox_device_id ON log_analysis_result (netbox_device_id)',
    'CREATE INDEX ix_log_analysis_result_related_sample_id ON log_analysis_result (related_sample_id)',
    'CREATE INDEX ix_log_analysis_result_site_id ON log_analysis_result (site_id)',
    'CREATE INDEX ix_log_analysis_result_id ON log_analysis_result (id)',
    'CREATE INDEX idx_analysis_status ON log_analysis_result (site_id, status, created_at)',
    'CREATE INDEX idx_analysis_site_device ON log_analysis_result (site_id, netbox_device_id)',
    'CREATE TABLE local_ticket (\n\tid SERIAL NOT NULL, \n\tticket_code VARCHAR(64) NOT NULL, \n\tprovider VARCHAR(32) NOT NULL, \n\tevent_id BIGINT, \n\tsource_event_id BIGINT, \n\ttitle VARCHAR(512) NOT NULL, \n\tdescription TEXT, \n\tpriority VARCHAR(30) NOT NULL, \n\trequester VARCHAR(120) NOT NULL, \n\tstatus VARCHAR(30) NOT NULL, \n\tmetadata JSON, \n\tclosed_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tupdated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(source_event_id) REFERENCES source_event (id)\n)',
    'CREATE UNIQUE INDEX ix_local_ticket_ticket_code ON local_ticket (ticket_code)',
    'CREATE INDEX idx_local_ticket_status_time ON local_ticket (status, created_at)',
    'CREATE INDEX ix_local_ticket_status ON local_ticket (status)',
    'CREATE INDEX idx_local_ticket_event_provider ON local_ticket (event_id, provider)',
    'CREATE INDEX ix_local_ticket_source_event_id ON local_ticket (source_event_id)',
    'CREATE INDEX ix_local_ticket_id ON local_ticket (id)',
    'CREATE INDEX ix_local_ticket_provider ON local_ticket (provider)',
    'CREATE INDEX ix_local_ticket_priority ON local_ticket (priority)',
    'CREATE INDEX ix_local_ticket_created_at ON local_ticket (created_at)',
    'CREATE INDEX idx_local_ticket_source_event_provider ON local_ticket (source_event_id, provider)',
    'CREATE INDEX ix_local_ticket_event_id ON local_ticket (event_id)',
    'CREATE TABLE case_record (\n\tid BIGSERIAL NOT NULL, \n\tcase_code VARCHAR(64) NOT NULL, \n\ttitle VARCHAR(512) NOT NULL, \n\tsummary TEXT, \n\tsource_event_id BIGINT, \n\tsite_id INTEGER, \n\tnetbox_device_id INTEGER, \n\tdevice_ip VARCHAR(64), \n\thost VARCHAR(255), \n\tpriority VARCHAR(20), \n\trisk_level VARCHAR(20), \n\tstatus casestatus NOT NULL, \n\tcurrent_phase VARCHAR(50), \n\tcase_metadata JSON, \n\topened_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tlast_activity_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tclosed_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tupdated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(source_event_id) REFERENCES source_event (id), \n\tFOREIGN KEY(site_id) REFERENCES site (id)\n)',
    'CREATE INDEX ix_case_record_last_activity_at ON case_record (last_activity_at)',
    'CREATE INDEX ix_case_record_risk_level ON case_record (risk_level)',
    'CREATE INDEX ix_case_record_device_ip ON case_record (device_ip)',
    'CREATE INDEX ix_case_record_host ON case_record (host)',
    'CREATE INDEX ix_case_record_id ON case_record (id)',
    'CREATE INDEX ix_case_record_priority ON case_record (priority)',
    'CREATE INDEX ix_case_record_current_phase ON case_record (current_phase)',
    'CREATE INDEX ix_case_record_created_at ON case_record (created_at)',
    'CREATE INDEX ix_case_record_source_event_id ON case_record (source_event_id)',
    'CREATE INDEX idx_case_record_status_phase ON case_record (status, current_phase, opened_at)',
    'CREATE INDEX ix_case_record_site_id ON case_record (site_id)',
    'CREATE INDEX ix_case_record_status ON case_record (status)',
    'CREATE INDEX ix_case_record_opened_at ON case_record (opened_at)',
    'CREATE INDEX idx_case_record_site_device ON case_record (site_id, netbox_device_id, opened_at)',
    'CREATE UNIQUE INDEX ix_case_record_case_code ON case_record (case_code)',
    'CREATE INDEX ix_case_record_netbox_device_id ON case_record (netbox_device_id)',
    'CREATE TABLE evidence_item (\n\tid BIGSERIAL NOT NULL, \n\tcase_id BIGINT NOT NULL, \n\tsource_event_id BIGINT, \n\tevidence_type evidencetype NOT NULL, \n\tsource_system VARCHAR(50) NOT NULL, \n\tsource_ref VARCHAR(255), \n\tfingerprint VARCHAR(128), \n\tdevice_ip VARCHAR(64), \n\thost VARCHAR(255), \n\toccurred_at TIMESTAMP WITH TIME ZONE, \n\tcollected_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tfreshness_seconds FLOAT, \n\tconfidence FLOAT, \n\traw_ref VARCHAR(255), \n\tsummary TEXT, \n\tpayload JSON, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(case_id) REFERENCES case_record (id), \n\tFOREIGN KEY(source_event_id) REFERENCES source_event (id)\n)',
    'CREATE INDEX ix_evidence_item_id ON evidence_item (id)',
    'CREATE INDEX idx_evidence_source_fingerprint ON evidence_item (source_system, fingerprint)',
    'CREATE INDEX ix_evidence_item_source_system ON evidence_item (source_system)',
    'CREATE INDEX ix_evidence_item_fingerprint ON evidence_item (fingerprint)',
    'CREATE INDEX ix_evidence_item_evidence_type ON evidence_item (evidence_type)',
    'CREATE INDEX ix_evidence_item_occurred_at ON evidence_item (occurred_at)',
    'CREATE INDEX ix_evidence_item_case_id ON evidence_item (case_id)',
    'CREATE INDEX ix_evidence_item_source_ref ON evidence_item (source_ref)',
    'CREATE INDEX ix_evidence_item_created_at ON evidence_item (created_at)',
    'CREATE INDEX ix_evidence_item_host ON evidence_item (host)',
    'CREATE INDEX ix_evidence_item_collected_at ON evidence_item (collected_at)',
    'CREATE INDEX idx_evidence_case_type ON evidence_item (case_id, evidence_type, created_at)',
    'CREATE INDEX ix_evidence_item_device_ip ON evidence_item (device_ip)',
    'CREATE INDEX ix_evidence_item_source_event_id ON evidence_item (source_event_id)',
    'CREATE TABLE agent_run (\n\tid BIGSERIAL NOT NULL, \n\tcase_id BIGINT NOT NULL, \n\tagent_type agenttype NOT NULL, \n\tagent_name VARCHAR(120) NOT NULL, \n\tstatus agentrunstatus NOT NULL, \n\tinput_payload JSON, \n\toutput_payload JSON, \n\tstarted_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\tduration_ms INTEGER, \n\terror_message TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(case_id) REFERENCES case_record (id)\n)',
    'CREATE INDEX ix_agent_run_status ON agent_run (status)',
    'CREATE INDEX ix_agent_run_case_id ON agent_run (case_id)',
    'CREATE INDEX ix_agent_run_id ON agent_run (id)',
    'CREATE INDEX ix_agent_run_created_at ON agent_run (created_at)',
    'CREATE INDEX ix_agent_run_agent_type ON agent_run (agent_type)',
    'CREATE INDEX ix_agent_run_agent_name ON agent_run (agent_name)',
    'CREATE INDEX idx_agent_run_case_type ON agent_run (case_id, agent_type, started_at)',
    'CREATE INDEX ix_agent_run_started_at ON agent_run (started_at)',
    'CREATE TABLE memory_entry (\n\tid BIGSERIAL NOT NULL, \n\tcase_id BIGINT, \n\tmemory_type memorytype NOT NULL, \n\tmemory_key VARCHAR(128) NOT NULL, \n\ttitle VARCHAR(255) NOT NULL, \n\tsummary TEXT, \n\tsource VARCHAR(50) NOT NULL, \n\ttags JSON, \n\tconfidence FLOAT, \n\tsuccess_score FLOAT, \n\tcontent JSON, \n\tembedding JSON, \n\tlast_accessed_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tupdated_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(case_id) REFERENCES case_record (id)\n)',
    'CREATE INDEX ix_memory_entry_source ON memory_entry (source)',
    'CREATE INDEX ix_memory_entry_id ON memory_entry (id)',
    'CREATE INDEX idx_memory_type_key ON memory_entry (memory_type, memory_key)',
    'CREATE INDEX ix_memory_entry_memory_type ON memory_entry (memory_type)',
    'CREATE INDEX ix_memory_entry_created_at ON memory_entry (created_at)',
    'CREATE INDEX ix_memory_entry_memory_key ON memory_entry (memory_key)',
    'CREATE INDEX idx_memory_source_created ON memory_entry (source, created_at)',
    'CREATE INDEX ix_memory_entry_case_id ON memory_entry (case_id)',
    'CREATE TABLE agent_claim (\n\tid BIGSERIAL NOT NULL, \n\tcase_id BIGINT NOT NULL, \n\tagent_run_id BIGINT NOT NULL, \n\tagent_type agenttype NOT NULL, \n\tclaim_type VARCHAR(100) NOT NULL, \n\tclaim_text TEXT NOT NULL, \n\tstatus claimstatus NOT NULL, \n\tconfidence FLOAT, \n\tevidence_refs JSON, \n\tgaps JSON, \n\tclaim_metadata JSON, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(case_id) REFERENCES case_record (id), \n\tFOREIGN KEY(agent_run_id) REFERENCES agent_run (id)\n)',
    'CREATE INDEX idx_agent_claim_case_type ON agent_claim (case_id, agent_type, created_at)',
    'CREATE INDEX ix_agent_claim_agent_type ON agent_claim (agent_type)',
    'CREATE INDEX ix_agent_claim_claim_type ON agent_claim (claim_type)',
    'CREATE INDEX ix_agent_claim_status ON agent_claim (status)',
    'CREATE INDEX ix_agent_claim_id ON agent_claim (id)',
    'CREATE INDEX ix_agent_claim_created_at ON agent_claim (created_at)',
    'CREATE INDEX ix_agent_claim_agent_run_id ON agent_claim (agent_run_id)',
    'CREATE INDEX ix_agent_claim_case_id ON agent_claim (case_id)',
    'CREATE TABLE remediation_plan (\n\tid BIGSERIAL NOT NULL, \n\tcase_id BIGINT NOT NULL, \n\tplan_code VARCHAR(64) NOT NULL, \n\tgenerated_by_agent_run_id BIGINT, \n\tstatus remediationplanstatus NOT NULL, \n\texecution_mode VARCHAR(20) NOT NULL, \n\tapproval_status VARCHAR(20) NOT NULL, \n\trisk_level VARCHAR(20) NOT NULL, \n\tsummary TEXT, \n\tplan_payload JSON, \n\trollback_payload JSON, \n\tsafety_checks JSON, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tupdated_at TIMESTAMP WITH TIME ZONE, \n\tapproved_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(case_id) REFERENCES case_record (id), \n\tFOREIGN KEY(generated_by_agent_run_id) REFERENCES agent_run (id)\n)',
    'CREATE UNIQUE INDEX ix_remediation_plan_plan_code ON remediation_plan (plan_code)',
    'CREATE INDEX ix_remediation_plan_generated_by_agent_run_id ON remediation_plan (generated_by_agent_run_id)',
    'CREATE INDEX ix_remediation_plan_approval_status ON remediation_plan (approval_status)',
    'CREATE INDEX ix_remediation_plan_case_id ON remediation_plan (case_id)',
    'CREATE INDEX ix_remediation_plan_execution_mode ON remediation_plan (execution_mode)',
    'CREATE INDEX ix_remediation_plan_risk_level ON remediation_plan (risk_level)',
    'CREATE INDEX idx_remediation_plan_case_status ON remediation_plan (case_id, status, created_at)',
    'CREATE INDEX ix_remediation_plan_created_at ON remediation_plan (created_at)',
    'CREATE INDEX ix_remediation_plan_status ON remediation_plan (status)',
    'CREATE INDEX ix_remediation_plan_id ON remediation_plan (id)',
    'CREATE TABLE execution_run (\n\tid BIGSERIAL NOT NULL, \n\tcase_id BIGINT NOT NULL, \n\tremediation_plan_id BIGINT NOT NULL, \n\texecutor_type VARCHAR(50) NOT NULL, \n\texecutor_name VARCHAR(120) NOT NULL, \n\tstatus executionrunstatus NOT NULL, \n\tcommand_summary TEXT, \n\trequest_payload JSON, \n\tresult_payload JSON, \n\taudit_trail JSON, \n\terror_message TEXT, \n\tstarted_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\tverified_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(case_id) REFERENCES case_record (id), \n\tFOREIGN KEY(remediation_plan_id) REFERENCES remediation_plan (id)\n)',
    'CREATE INDEX ix_execution_run_created_at ON execution_run (created_at)',
    'CREATE INDEX ix_execution_run_remediation_plan_id ON execution_run (remediation_plan_id)',
    'CREATE INDEX ix_execution_run_executor_type ON execution_run (executor_type)',
    'CREATE INDEX ix_execution_run_status ON execution_run (status)',
    'CREATE INDEX ix_execution_run_case_id ON execution_run (case_id)',
    'CREATE INDEX ix_execution_run_started_at ON execution_run (started_at)',
    'CREATE INDEX ix_execution_run_executor_name ON execution_run (executor_name)',
    'CREATE INDEX idx_execution_run_plan_status ON execution_run (remediation_plan_id, status, started_at)',
    'CREATE INDEX ix_execution_run_id ON execution_run (id)'
]

DOWNGRADE_STATEMENTS = [
    'DROP TABLE execution_run',
    'DROP TABLE remediation_plan',
    'DROP TABLE agent_claim',
    'DROP TABLE memory_entry',
    'DROP TABLE agent_run',
    'DROP TABLE evidence_item',
    'DROP TABLE case_record',
    'DROP TABLE local_ticket',
    'DROP TABLE log_analysis_result',
    'DROP TABLE source_event',
    'DROP TABLE ssh_credential_device_binding',
    'DROP TABLE raw_anomaly',
    'DROP TABLE automation_policy',
    'DROP TABLE log_sample',
    'DROP TABLE device_state',
    'DROP TABLE site_automation_switch',
    'DROP TABLE automation_setting',
    'DROP TABLE log_scope',
    'DROP TABLE integration_setting',
    'DROP TABLE asset_device',
    'DROP TABLE ssh_credential',
    'DROP TABLE site',
    'DROP TYPE sourceeventstatus',
    'DROP TYPE casestatus',
    'DROP TYPE evidencetype',
    'DROP TYPE agenttype',
    'DROP TYPE agentrunstatus',
    'DROP TYPE claimstatus',
    'DROP TYPE memorytype',
    'DROP TYPE remediationplanstatus',
    'DROP TYPE executionrunstatus'
]


def upgrade() -> None:
    for statement in UPGRADE_STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    for statement in DOWNGRADE_STATEMENTS:
        op.execute(statement)
